name = "sentinel"
main = "src/abuse_monitor.ts"
compatibility_date = "2024-11-24"

[[ d1_databases ]]
binding = "D1"
database_name = "tactical-curriculum-db"
database_id = "25f74a5f-6030-41a9-ae14-061a2e594e13"

[triggers]
crons = ["0 3 * * *"]  # Daily 03:00 UTC
